### ISSUE TITLE
Add flag to suppress OpenAPI change report

### ISSUE THREAD

**Issue by ahtrotta** [getappmap/analyze-action#34]
In non-API projects, there might still be OpenAPI changes reported. Provide an analysis flag to disable these. [Example from AppMap IntelliJ Plugin](https://github.com/getappmap/appmap-intellij-plugin/pull/389)

**Comment by kgilpin** [comment]
This is available with the option `exclude-sections`

https://github.com/getappmap/analyze-action/blob/main/action.yml#L53
